trigger: none  # Bu pipeline sadece manuel ya da başka bir pipeline tarafından tetiklenir

resources:
  pipelines:
    - pipeline: WeatherPipeline
      source: Weather  # Weather pipeline adını buraya yazın
      trigger: true

pool:
  vmImage: 'ubuntu-latest'

steps:
- download: current
  artifact: sync-files

- task: Checkout@1
  inputs:
    repository: 'self'
    persistCredentials: true

- script: |
    echo "Applying changes to WeatherPROD"
    cp -r $(Pipeline.Workspace)/sync-files/* .
    git add .
    git commit -m "Sync from Weather repository"
    git push
  displayName: 'Sync Changes to WeatherPROD'
